name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2.3.4

    - name: Cache nix store
      id: cache-nix
      uses: actions/cache@v2
      with:
        path: /nix/store
        key: nix-${{ hashFiles('shell.nix') }}-${{ hashFiles('nix/**') }}

    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-20.09

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - run: nix-shell --command "cargo test"
